name: Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Build Targets
      run: |
        rustup target add thumbv7em-none-eabihf
        rustup target add thumbv8m.main-none-eabihf
    - name: Build for Nucleo-F413Zh
      run: cargo build --verbose --release --no-default-features -F nucleo-f413zh --target thumbv7em-none-eabihf
    - name: Build for RP Pico2
      run: cargo build --verbose --release --no-default-features -F rp-pico --target thumbv8m.main-none-eabihf
    - uses: actions/upload-artifact@v4
      with:
        name: Nucleo-F413ZH firmware
        path: target/thumbv7em-none-eabihf/release/sensor-kit
    - uses: actions/upload-artifact@v4
      with:
        name: RP Pico2 firmware
        path: target/thumbv8m.main-none-eabihf/release/sensor-kit
